# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :bump do
    version_name = "1.0"

    # Incremental sequence number
    android_set_version_code(gradle_file: "app/build.gradle")

    android_set_version_name(
      version_name: version_name,
      gradle_file: "app/build.gradle"
    )
  end

  lane :distribute do
    build_android_app(
      task: "assemble",
      build_type: "Debug"
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_ANDROID_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      groups: "users",
    )
  end
end
