name: Build And Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - AndroidApp/**

env:
  FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  build_and_release:
    name: Build And Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          working-directory: AndroidApp
          ruby-version: 2.7
          bundler-cache: true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./AndroidApp/app/google-services.json

      - name: Fastlane Distribute
        working-directory: AndroidApp
        run: bundle exec fastlane distribute

